name: Bitbank DCA (Dry Run)

on:
  schedule:
    # UTCで指定。毎日日本時間の午前9時に実行
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: dca-dry-run
  cancel-in-progress: true

jobs:
  dryrun:
    runs-on: ubuntu-latest

    env:
      # ← ここで .env を使わず直接渡す
      BITBANK_API_KEY: ${{ secrets.BITBANK_API_KEY }}
      BITBANK_API_SECRET: ${{ secrets.BITBANK_API_SECRET }}
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_TO_USER_ID: ${{ secrets.LINE_TO_USER_ID }}

      # 任意の変数（あれば）
      DCA_TOTAL_JPY: ${{ vars.DCA_TOTAL_JPY }}
      GUARD_DIP_THRESHOLD: ${{ vars.DCA_GUARD_DIP_THRESHOLD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dry run execution
        run: |
          python -m app.main --dry-run