
name: Weekly DCA (Bitbank)

on:
  schedule:
    - cron: "0 22 * * 0"  # Sun 22:00 UTC = Mon 07:00 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DCA
        env:
          TOTAL_JPY: ${{ vars.TOTAL_JPY }}
          PAIRS: ${{ vars.PAIRS }}
          WEIGHTS: ${{ vars.WEIGHTS }}
          SLIPPAGE_PCT: ${{ vars.SLIPPAGE_PCT }}
          SPREAD_MAX_PCT: ${{ vars.SPREAD_MAX_PCT }}
          VOL5M_MAX_PCT: ${{ vars.VOL5M_MAX_PCT }}
          DIP_TRIGGER_PCT: ${{ vars.DIP_TRIGGER_PCT }}
          DIP_MULTIPLIER: ${{ vars.DIP_MULTIPLIER }}
          LOW_BALANCE_ALERT_JPY: ${{ vars.LOW_BALANCE_ALERT_JPY }}
          TIME_WINDOW_MS: ${{ vars.TIME_WINDOW_MS }}
          AUTH_MODE: ${{ vars.AUTH_MODE }}
          BITBANK_API_KEY: ${{ secrets.BITBANK_API_KEY }}
          BITBANK_API_SECRET: ${{ secrets.BITBANK_API_SECRET }}
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: |
          python -m app.main --dry-run
